name = "onde-surf"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "onde-surf-db"
database_id = "e7845b27-a3f3-4d70-8078-0b05bbef3283"
