name = "onde-surf"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

[assets]
directory = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "onde-surf-db"
database_id = "e7845b27-a3f3-4d70-8078-0b05bbef3283"

[[routes]]
pattern = "onde.surf/*"
zone_name = "onde.surf"

[[routes]]
pattern = "www.onde.surf/*"
zone_name = "onde.surf"
